config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end

  # Defines the root path route ("/")
  # root "articles#index"
  root "users#index", as: 'home'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.admin?
      can :manage, :all
    else
      can :read, :all
      can :manage, Post, author_id: user.id
      can :manage, Comment, author_id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_comments_counter
  after_destroy :delete_posts_counter

  private

  def update_comments_counter
    post.update(comments_counter: post.comments.length)
  end

  def delete_posts_counter
    post.decrement!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  after_save :update_likes_counter
  belongs_to :author, class_name: 'User'
  belongs_to :post,
             private

  def update_likes_counter
    post.update(likes_counter: post.likes.length)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :comments, class_name: 'Comment', foreign_key: 'post_id'
  has_many :likes, class_name: 'Like', foreign_key: 'post_id'

  after_save :update_posts_counter
  after_destroy :delete_posts_counter

  validates :text, presence: true
  validates :title, presence: true, length: { in: 3..250 }
  validates :comments_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def last_five_comments
    comments.includes(:author).order(created_at: :desc).limit(5)
  end

  private

  def update_posts_counter
    author.increment!(:postCounter)
  end

  def delete_posts_counter
    author.decrement!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :comments, class_name: 'Comment', foreign_key: 'author_id'
  has_many :posts, class_name: 'Post', foreign_key: 'author_id'
  has_many :likes, class_name: 'Like', foreign_key: 'author_id'

  validates :name, presence: true
  validates :postCounter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def admin?
    role == 'admin'
  end

  def last_three_posts
    posts.order('created_at Desc').limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  # Catch all CanCan errors and alert the user of the exception
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end

  def after_sign_out_path_for(_scope)
    new_user_session_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[email name password password_confirmation])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource
  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.author = current_user
    @comment.post = Post.find(params[:post_id])

    respond_to do |_format|
      if @comment.save

        redirect_to user_post_path(user_id: params[:user_id], id: params[:post_id])
      else
        render :new
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])

    if @comment.destroy
      redirect_to user_post_path(user_id: current_user.id, id: @comment.post_id), notice: 'Comment deleted successfully'
    else
      flash.new[:alert] = @comment.errors.full_messages.first if @comment.errors.any?
      render :show, status: 400
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.new
    @like.author = current_user
    @like.post = Post.find(params[:post_id])
    @like.save!
    redirect_to user_post_path(user_id: params[:user_id], id: params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.order(created_at: :asc)
  end

  def show
    @user = User.includes(:posts, posts: [:comments, { comments: [:author] }]).find(params[:user_id])
    @post = @user.posts.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user

    respond_to do |_format|
      if @post.save
        redirect_to user_posts_path(current_user)
      else
        render :new
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])

    if @post.destroy
      redirect_to user_posts_path(current_user), notice: 'Post deleted successfully'
    else
      flash.new[:alert] = @post.errors.full_messages.first if @post.errors.any?
      render :show, status: 400
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  def index
    @users = User.all.order(id: :asc)
  end

  def show
    @user = User.find(params[:id])
    @last_three_posts = @user.last_three_posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<section class="new_comment_container">
  <%= form_with model: @comment, url: user_post_comments_path, local: true do |form| %>
    <%= form.text_field :text, class: "comment_field", placeholder: "Enter a text here" %>
    <%= form.submit "Add comment", class: "submit-btn btn" %>
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "users", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "posts", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "comment", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "login", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="app">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <% if user_signed_in? %>
        <%=  link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete } %>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/index.html.erb
<section class="posts_container">
  <%= render partial: "shared/user", locals: {user: @user || "No users found"} %>
  <% @posts.each do |post| %>
      <%= render partial: 'shared/post', locals: { post: post, show_full_post: false } %>
      <div class="recent_comments_container">
        <% post.last_five_comments.each do |comment| %>
          <%= render partial: 'shared/comment', locals: { comment: comment } %>
        <% end %>
      </div>
  <% end %>
  <button type="button" class="btn">Pagination</button> 
</section>

app/views/posts/new.html.erb
<section class="new_post_container">
  <%= render partial: "shared/form", locals: { post: @post } %> 
</section>

app/views/posts/show.html.erb
<section class="com_post_container">
  <%= render partial: "shared/like", locals: { like: Like.new, post_id: @post.id, user_id: @post.author.id } %>
  <%= render partial: 'shared/post', locals: { post: @post, show_full_post: true } %>
  <div class="com_comments_container">
    <% @post.comments.each do |comment| %>
      <%= render partial: 'shared/comment', locals: { comment: comment } %>
      <% if can? :delete, comment %>
      <button type="button" class="delete_btn btn"><%= link_to "Delete Comment", user_post_comment_path(user_id: comment.author.id, post_id: comment.post.id, id: comment.id), data: { turbo_method: :delete } %></button>
    <% end %>
    <% end %>
  </div>
  <button type="button" class="create_post_btn btn"><%= link_to "Add a new comment", new_user_post_comment_path(user_id: @post.author.id, post_id: @post.id) %></button>
</section>

app/views/shared/_comment.html.erb
<div class="comment_container">
  <p class="comment_date"><%= comment.author.name %>: </p>
  <p class="comment_body"><%= comment.text %></p>
</div>

app/views/shared/_form.html.erb
<%= form_with model: @post, url: user_posts_path, local: true do |form| %>
  <%= form.text_field :title, class: "form_title", placeholder: "Enter a title here" %>
  <%= form.text_area :text, class: "form_text", placeholder: "Enter a text here" %>
  <%= form.submit "Submit", class: "submit-btn btn" %>
<% end %>

app/views/shared/_like.html.erb
<section class="new_like">
  <%= form_with model: @like, url: user_post_likes_path(user_id: @user, post_id: @post), local: true do |form| %>
    <%= form.submit "Like", class: "like_btn btn" %>
  <% end %>
</section>

app/views/shared/_post.html.erb
<%= link_to user_post_path(user_id: post.author.id, id: post.id), class: "post_partial" do %>
<div class="post_container">
<h2 class="post_title"> Post # <%= post.id %>: <%= post.title %> </h2>
  <% if (show_full_post) %>
    <p class="post_text"><%= post.text %></p>
  <% else %>
    <p class="post_text"><%= truncate(post.text, length: 250, omission: "...") %></p>
  <% end %>
  <div class="post_stats">
    <p>Comments: <%= post.comments_counter || 0 %></p>
    <p>Likes: <%= post.likes_counter || 0 %></p>
  </div>
</div>

<% if can? :delete, @post %>
<button type="button" class="delete_btn btn"><%= link_to "Delete Post", user_post_path(user_id: @post.author.id, id: @post.id), data: { turbo_method: :delete } %></button>
<% end %>

<% end %>

app/views/shared/_user.html.erb
<div class="user_container">
  <div class="user_img">
    <img src=<%= user.photo%> alt="<%= user.name %>'s photo">
  </div>
  <div class="user_highlights">
  <h2><%= link_to  user.name, user_path(user) %></h2>
  <p>Number of posts: <%= user.postCounter || 0 %></p>
  </div>
</div>

app/views/users/index.html.erb
<section class="users_container">
  <div>
    <%= render partial: "shared/user", collection: @users, as: :user || ">No users found" %>
  </div>
</section>

app/views/users/show.html.erb
<section class="a_user_container">
  <%= render partial: "shared/user", locals: {user: @user} %>

  <div class="user_bio">
    <h3>Bio</h3>
    <p><%= @user.bio %></p>
  </div>

  <% @last_three_posts.each do |post| %>
    <%= render partial: 'shared/post', locals: { post: post, show_full_post: false } %>
  <% end %>

  <div class="btn_container">
    <button type="button" class="btn"><%= link_to "See all Posts", user_posts_path(user_id: @user.id) %></button> 
    <button type="button" class="create_post_btn btn"><%= link_to "Create Post", new_user_post_path(user_id: @user.id) %>
  </div>
</section>